### ISSUE TITLE
Setup on macOS 11.6.2

### ISSUE THREAD

**Issue by mattsbennett** [FosolSolutions/coevent#1] opened 2021-12-25 22:10 UTC
## Issues

1. `make init` error output
```
bash: setup: command not found
make: *** [init] Error 127
```

2. After ^ resolved, `make init` error output:
```
Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "./entrypoint.sh": permission denied: unknown
```

3. After file permissions fix, still the same error output, and still, after `make clean`, same output.

4. After ^ resolved, `make init` error output
```
Build started...
Build succeeded.
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'User ID')
   at System.Data.Common.ADP.CheckArgumentNull(Object value, String parameterName)
   at System.Data.SqlClient.SqlConnectionStringBuilder.SetValue(String keyword, String value)
   at System.Data.SqlClient.SqlConnectionStringBuilder.set_UserID(String value)
   at Coevent.Dal.CoeventContextFactory.CreateDbContext(String[] args) in /Users/matthewbennett-work/Sites/coevent/api/libs/dal/CoeventContextFactory.cs:line 61
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContextFromFactory(Type factory, Type contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.<>c__DisplayClass21_2.<FindContextTypes>b__9()
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String connectionString, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabaseImpl(String targetMigration, String connectionString, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Exception has been thrown by the target of an invocation.
```

## Solutions

1. Resolved in the linked PR.
2. Resolved in the linked PR.
3. Resolved in the linked PR.
4. I'm not sure of the solution here. I tried adding the user/pw created on setup to `db/mssql/.env`, but that didn't seem to be it. I'm not sure what `(Parameter 'User ID')` is.

## Notes

I suspect this is expected - I also needed to:

- Install .NET 6 from https://dotnet.microsoft.com/en-us/download/dotnet/6.0 (locally)
- Run `dotnet tool update --global dotnet-ef`

**Comment by mattsbennett** [comment] 2021-12-25 22:26
@Fosol I'm not sure about 4. above - any thoughts?

**Comment by Fosol** [comment] 2021-12-27 14:47
I merged a PR which adds a `make nuke`.  I've ran this with a fresh install and I didn't run into any issues getting everything up and running.  #4 was caused by the `.env` files not being correctly populated with variable values.

Let me know if you're still running into an issue?

**Comment by mattsbennett** [comment] 2021-12-27 18:33
Tried the new `make nuke` (neat that it makes backups), but still running into the same issue from https://github.com/FosolSolutions/coevent/pull/3#issuecomment-1001098815 on `make init`.

**Comment by Fosol** [comment] 2021-12-27 22:47
@mattsbennett I should have thought of this at the beginning lol.  It's because you don't have `.net 6.0` SDK installed locally.  Which I doubt you want.  You can manually run in the Development Container if you want.  I'll make an update so it does it automatically for you.  Testing on my mac atm.

**Comment by mattsbennett** [comment] 2021-12-27 22:55
Ahh. I actually did install it locally, plus did the tools update, ran into other issues until I did that ha. I don’t us .net for anything else, so not a big deal. Hadn’t tried the devcontainers yet though, should have tried that 🤦

---
Matt Bennett

**Closed as completed** 2021-12-27 23:45 UTC
Labels: bug

**Comment by Fosol** [comment] 2021-12-28 00:00
This should now work with the new `make db-update` command.  It creates a docker container to run the command in.  Make sure your `connectionstring.json` is using the correct network path.  Recreate it if you need to.
